---
# tasks file for pwydymus
#
- hosts: localhost
  vars:
    repo_pp_branch: devel
    merge_pp_branch_to: pwy20200308-02
    source_git_repos_dir: https://github.com/motaboy-bb/ansible-sandbox.git

  tasks:
  - name: Blad
    git:
      repo: "{{ source_git_repos_dir }}"
      version: master
      dest: .